# -- coding: utf-8 --

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    flag_turbidity = ph = 0
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(380, 140, 311, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label2 = QtWidgets.QLabel(self.centralwidget)
        self.label2.setGeometry(QtCore.QRect(550, 320, 311, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label2.setFont(font)
        self.label2.setObjectName("label2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(550, 240, 113, 29))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(555, 280, 106, 30))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(lambda: self.clicked(f'{self.label.text()}'))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.pushButton2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton2.setGeometry(QtCore.QRect(1000, 600, 106, 30))
        self.pushButton2.setObjectName("pushButton2")
        self.pushButton2.setText('Recomeçar')
        self.pushButton2.clicked.connect(self.reset)
        self.pushButton2.setVisible(False)


        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def reset(self):
        self.label.setText('Digite o valor do ph [3 - 9.5]:')
        self.label.adjustSize()
        self.label2.clear()
        self.lineEdit.clear()
        self.ph = 0
        self.flag_turbidity = 0
        self.pushButton2.setVisible(False)
        self.pushButton.setEnabled(True)
        self.lineEdit.setEnabled(True)

    def clicked(self, label_string: str):
        if label_string == 'Digite o valor do ph [3 - 9.5]:':
            try:
                self.ph = float(self.lineEdit.text())
                if self.ph <= 5.6 or self.ph > 6.8:
                    self.label2.setText('Qualidade: baixa')
                    self.pushButton2.setVisible(True)
                    self.pushButton.setEnabled(False)
                    self.lineEdit.setEnabled(False)
                else:
                    self.label.setText('Digite a gordura do leite(0 - sem gordura/1 - com gordura):')
                    self.label.adjustSize()
                    self.lineEdit.clear()
                    self.label2.clear()
            except ValueError:
                self.label2.setText('Valor invalido!')
        elif label_string == 'Digite a gordura do leite(0 - sem gordura/1 - com gordura):':
            try:
                fat = int(self.lineEdit.text())
                if fat == 0:
                    self.label.setText('Digite a temperatura do leite [34C - 95C]:')
                    self.label.adjustSize()
                    self.lineEdit.clear()
                    self.label2.clear()
                elif fat == 1:
                    self.label.setText('Digite a turvidez do leite(0 - não turvo/1 - turvo):')
                    self.label.adjustSize()
                    self.lineEdit.clear()
                    self.label2.clear()
                else:
                    self.label2.setText('Valor invalido!')

            except ValueError:
                self.label2.setText('Valor invalido!')
        elif label_string == 'Digite a temperatura do leite [34C - 95C]:':
            if self.flag_turbidity == 0:
                try:
                    temp = int(self.lineEdit.text())
                    if temp <= 45:
                        self.label2.setText('Qualidade: média')
                        self.pushButton2.setVisible(True)
                        self.pushButton.setEnabled(False)
                        self.lineEdit.setEnabled(False)
                    elif temp <= 95:
                        self.label2.setText('Qualidade: baixa')
                        self.pushButton2.setVisible(True)
                        self.pushButton.setEnabled(False)
                        self.lineEdit.setEnabled(False)
                    else:
                        self.label2.setText('Valor invalido!')
                except ValueError:
                    self.label2.setText('Valor invalido!')
            else:
                try:
                    temp = int(self.lineEdit.text())
                    if 45 < temp < 95:
                        self.label2.setText('Qualidade: baixa')
                        self.pushButton2.setVisible(True)
                        self.pushButton.setEnabled(False)
                        self.lineEdit.setEnabled(False)
                    elif temp < 45:
                        if self.ph <= 6.5:
                            self.label2.setText('Qualidade: média')
                            self.pushButton2.setVisible(True)
                            self.pushButton.setEnabled(False)
                            self.lineEdit.setEnabled(False)
                        elif temp <= 38:
                            self.label2.setText('Qualidade: alta')
                            self.pushButton2.setVisible(True)
                            self.pushButton.setEnabled(False)
                            self.lineEdit.setEnabled(False)
                        elif temp <= 41:
                            self.label2.setText('Qualidade: média')
                            self.pushButton2.setVisible(True)
                            self.pushButton.setEnabled(False)
                            self.lineEdit.setEnabled(False)
                        elif self.ph <= 6.7:
                            self.label2.setText('Qualidade: média')
                            self.pushButton2.setVisible(True)
                            self.pushButton.setEnabled(False)
                            self.lineEdit.setEnabled(False)
                        else:
                            self.label.setText('Digite o gosto(0 - ruim/1 - bom):')
                            self.label.adjustSize()
                            self.lineEdit.clear()
                            self.label2.clear()

                    else:
                        self.label2.setText('Valor invalido!')
                except ValueError:
                    self.label2.setText('Valor invalido!')
        elif label_string == 'Digite a turvidez do leite(0 - não turvo/1 - turvo):':
            self.flag_turbidity = 1
            try:
                turbidity = int(self.lineEdit.text())
                if turbidity == 1:
                    self.label2.setText('Qualidade: alta')
                    self.pushButton2.setVisible(True)
                    self.pushButton.setEnabled(False)
                    self.lineEdit.setEnabled(False)
                else:
                    self.label.setText('Digite a temperatura do leite [34C - 95C]:')
                    self.label.adjustSize()
                    self.lineEdit.clear()
                    self.label2.clear()
            except ValueError:
                self.label2.setText('Valor invalido!')
        elif label_string == 'Digite o gosto(0 - ruim/1 - bom):':
            try:
                taste = int(self.lineEdit.text())
                if taste == 0:
                    self.label2.setText('Qualidade: média')
                    self.pushButton2.setVisible(True)
                    self.pushButton.setEnabled(False)
                    self.lineEdit.setEnabled(False)
                elif taste == 1:
                    self.label2.setText('Qualidade: alta')
                    self.pushButton2.setVisible(True)
                    self.pushButton.setEnabled(False)
                    self.lineEdit.setEnabled(False)
                else:
                    self.label2.setText('Valor inválido!')
            except ValueError:
                self.label2.setText('Valor inválido!')


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Qualidade do leite"))
        self.label.setText(_translate("MainWindow", "Digite o valor do ph [3 - 9.5]:"))
        self.label.adjustSize()
        self.pushButton.setText(_translate("MainWindow", "Enviar"))
